---
title: "The Function of Hypothalamic Preoptic Region of Sleeping and XX Behaviors in Mouse"
author: "Gun Jang, Jiaying (Tina) Wu, Zhendao (Jason) Li, Misael Lazaro Trigo"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    citation_package: natbib
    latex_engine: pdflatex
header-includes:
  - \usepackage{hyperref}
  - \usepackage{titlesec}
  - \titleformat{\section}{\normalfont\Large\bfseries}{\hyperlink{toc}{\thesection}}{1em}{}
---

```{r,include=FALSE}
library(tidyverse)
library(gridExtra)
library(png)
library(grid)
library(patchwork)
library(cowplot)
df<-read.csv("merfish_all_cells.csv")
```

```{r,out.width="100%"}
df_filt<-df[df$Animal_ID%in%c(12,18,25,28),]

df_filt$Animal_ID<-ifelse(df_filt$Animal_ID==12,"Male: Parenting",
                          ifelse(df_filt$Animal_ID==18,"Female: Parenting",
                                 ifelse(df_filt$Animal_ID==25,"Female: Mating",
                                        "Male: Mating")))


plotter<-function(df,ct,ids){
  df_filt<-df[df$Animal_ID%in%ids,]
  df_ct<-df_filt[df_filt$Neuron_cluster_ID%in%ct,]

  pt<-ggplot()+
    geom_point(data=df_filt,aes(x=Centroid_X,y=Centroid_Y),shape=18,alpha=.07)+
    geom_point(data=df_ct,aes(x=Centroid_X,y=Centroid_Y,color=as.factor(Neuron_cluster_ID)),shape=16)+
    facet_wrap(~Animal_ID+Bregma,scales="free",ncol=length(unique(df_ct$Bregma)),
               labeller=label_bquote(cols=.(Animal_ID)~", Bregma:"~.(Bregma)))+
    theme(panel.background=element_rect(fill='transparent'),
          axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          aspect.ratio=1)+
    scale_color_discrete(name="Clusters")
  pt
}

saver<-function(df,ct,ids,name){
  nm<-paste0(name,".png")
  ggsave(nm,
         plotter(df,ct,ids),
         width=15,height=15,units="in")
}

#to see here on Rstudio
#plotter(df,c("I-5","E-3", "E-10"),c(12,18,25,28))
#to save in your local drive
saver(df_filt,c("I-5","E-3","E-10"),
      c("Male: Parenting","Female: Parenting","Female: Mating","Male: Mating"),
      "VLPO")
saver(df_filt,c("I-44","E-13","E-7"),
      c("Male: Parenting","Female: Parenting","Female: Mating","Male: Mating"),
      "MnPO")
saver(df_filt,c("I-14","E-8"),
      c("Male: Parenting","Female: Parenting","Female: Mating","Male: Mating"),
      "CCK")
saver(df_filt,c("I-23","I-35","E-20"),
      c("Male: Parenting","Female: Parenting","Female: Mating","Male: Mating"),
      "CRH")
saver(df_filt,c("E-3","E-31","E-30","I-14","I-24"),
      c("Male: Parenting","Female: Parenting","Female: Mating","Male: Mating"),
      "Misael")
```

