---
title: "Title"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    citation_package: natbib
    latex_engine: pdflatex
header-includes:
  - \usepackage{hyperref}
  - \usepackage{titlesec}
  - \titleformat{\section}{\normalfont\Large\bfseries}{\hyperlink{toc}{\thesection}}{1em}{}
---

\newpage

```{r,include=FALSE}
#All the codes below will not show up on the knitted pdf document. 
library(Seurat)
library(monocle3)
library(SeuratData)
library(SeuratWrappers)
library(tidyverse)
library(patchwork)
library(magrittr)
library(SpatialExperiment)
library(STexampleData)
library(ggspavis)
library(scran)
library(nnSVG)
library(MerfishData)
library(ExperimentHub)
library(scater)
library(ggplot2)
```

```{r,include=FALSE}
# Since we are using updated version of Seurat, make sure to change genes.tsv.gz to features.tsv.gz. 
# Not needed for what we wanted so far. 
data<-Read10X(data.dir="./")
# Renamed dataset to more straight forward name. 
data2<-read.csv("merfish_all_cells.csv")
```

```{r,include=FALSE}
df<-data2
head(df)
plotter<-function(df,ct=NULL){
  df_filt<-df[df$Neuron_cluster_ID%in%ct,]
  breg<-unique(df$Bregma)
  lapply(breg,function(breg){
    ggplot()+
      geom_point(data=df,aes(x=Centroid_X,y=Centroid_Y))+
      labs(title=paste("Bregma Level:", breg),
           x="Centroid X",
           y="Centroid Y")
    if(!is.null(ct)){
      pt<-pt+
        geom_point(data=df_filt[df_filt$Bregma==breg,],
                   aes(x=Centroid_X,y=Centroid_Y,color=Neuron_cluster_ID))
    }
    pt
  })
}
plotter(df)
```


```{r,include=FALSE}
data22<-data2#[!apply(data2,1,function(x) any(is.na(x))),]
#Need to remove NAs if we want to run logNormCounts() to calculate PCA. Otherwise, not needed.
#Removing NAs will reduce the unique Bregma to 4 from 12
#To remove NAs, simply remove hashtag above after data2. 
ass<-list(counts=t(data22[,10:ncol(data22)]))
col<-data22[,4:9]
spe<-SpatialExperiment(assays=ass,
                       colData=col,
                       spatialCoordsNames=c("Centroid_X","Centroid_Y"))
```

```{r,include=FALSE}
spe<-addPerCellQC(spe)
spe<-computeLibraryFactors(spe)
#Cannot run the following two lines unless NAs are removed. 
#spe<-logNormCounts(spe)
#spe<-runPCA(spe)

scRNA<-CreateSeuratObject(counts=data)
scRNA<-NormalizeData(scRNA)
scRNA<-FindVariableFeatures(scRNA)
scRNA<-ScaleData(scRNA)
scRNA<-RunPCA(scRNA)

merfish<-data2[,10:ncol(data2)]
# When running `FindVariableFeatures(), NAs are not allowed, hence removed. 
merfish<-merfish[!apply(merfish,1,function(x) any(is.na(x)|!is.numeric(x))),]
merfish_seurat<-CreateSeuratObject(counts=merfish)
merfish_seurat<-NormalizeData(merfish_seurat)
merfish_seurat<-FindVariableFeatures(merfish_seurat)
merfish_seurat<-ScaleData(merfish_seurat)
merfish_seurat<-RunPCA(merfish_seurat)

# Function to determine the number of PCA. 
elbowNum<-function(obj,threshold=.9){
  a<-obj[["pca"]]
  stdev<-a@stdev
  var<-cumsum(stdev^2)/sum(stdev^2)
  which(var>=threshold)[1]
}
# Calculates elbow point that exceeds .9, and dimension will be 1 to maximum of two seurat objects. 
n1<-elbowNum(scRNA,.9)
n2<-elbowNum(merfish_seurat,.9)
ds<-1:(max(n1,n2))
unique(colData(spe)$Bregma)
unique(colData(spe)$Neuron_cluster_ID)
unique(colData(spe)$Behavior)
```


```{r,include=FALSE}
#Function to subset spe using behavior. 
subsetSpe<-function(d=spe,b){
  d[,colData(d)$Behavior%in%b]
}
#Examples of subsetted data. 
#d1 subsetted data which contains Parenting and d2 with Mating. 
d1<-subsetSpe(spe,c("Parenting","Virgin Parenting"))
d2<-subsetSpe(spe,"Mating")

#The below is a function to draw the plot. 
ctPlot<-function(d=spe,ct,bg=c(0.26,0.21,0.16,0.11,0.06,0.01,-0.04,
                               -0.09,-0.14,-0.19,-0.24,-0.29)){
  temp<-d[,colData(d)$Bregma%in%bg]
  ctTemp<-colData(temp)$Neuron_cluster_ID
  ctTemp[ctTemp%in%ct]<-ctTemp[ctTemp%in%ct]
  ctTemp[!ctTemp%in%ct]<-"Other"
  colData(temp)$cluster<-ctTemp
  plotSpots(temp,
            annotate="cluster",
            in_tissue=NULL)+
    #change ncol= value to change the number of plots in each row.
    facet_wrap(~Bregma,ncol=4)
}
#Example of ctPlot (Cluster Plot).
#The first argument is the object you want to plot. 
#The second argument is the clusters you want to highlight. Any clusters that is not in the list will be named as "Other"
#the third argument is the Bregma you want. If you look at the figure 5, I can make a rough guess that since 0.26 means 0 micrometer, .12 unit decrease means 100 micrometer increase. You can choose which ones you want. If you do not want to bother, leave it blank. 
ctPlot(d1,c("I-5","I-6","I-9"),)
ctPlot(d2,c("I-5","I-6","I-9"),)
```




